// Regenerates src/remotion/fonts-data.ts by base64-embedding the vendored .woff2 files
// from public/fonts/. The composition loads fonts from these data URIs (no in-sandbox
// HTTP fetch), which is what makes multi-photo renders immune to the font delayRender
// timeout. Run `node scripts/embed-fonts.mjs` after changing any font file.
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const FONTS = path.join(ROOT, "public", "fonts");
const OUT = path.join(ROOT, "src", "remotion", "fonts-data.ts");

// filename -> exported constant name
const MAP = [
  ["PlayfairDisplay-500.woff2", "PLAYFAIR_500"],
  ["PlayfairDisplay-600.woff2", "PLAYFAIR_600"],
  ["PlayfairDisplay-500Italic.woff2", "PLAYFAIR_500_ITALIC"],
  ["Inter-600.woff2", "INTER_600"],
];

const lines = [
  "// GENERATED by scripts/embed-fonts.mjs — do not edit by hand.",
  "// The ListingVideo composition's fonts, base64-embedded as woff2 data URIs so the",
  "// render loads them with zero network fetch (a FontFace url('data:...') source),",
  "// eliminating the loadFont delayRender timeout under real multi-photo renders.",
  "// fonts-data.test.ts asserts each constant byte-matches its public/fonts/ source.",
  "",
];
for (const [file, name] of MAP) {
  const b64 = readFileSync(path.join(FONTS, file)).toString("base64");
  lines.push(`export const ${name} = "data:font/woff2;base64,${b64}";`);
}
writeFileSync(OUT, lines.join("\n") + "\n");
console.log(`wrote ${OUT} (${MAP.length} fonts embedded)`);
